### ISSUE TITLE
please create https://github.com/panicsteve/butt-to-butt

### ISSUE THREAD

**Issue by x1024** [panicsteve/cloud-to-butt#46]
Make it say something like "this isn't the butt you're looking for".

Rationale:
Users who already have the plugin installed will often go to this repository instead of https://github.com/panicsteve/cloud-to-butt
(e.g. when following the links in the Google webstore, that was where I ended up)

Obviously, it would be easy for the user to manually change the URL, but it's also a perfect opportunity to make a nice joke.

**Comment by mohammadg** [comment]
Haha this would be neat!

**Comment by panicsteve** [comment]
My version of this extension cannot cause that URL rewrite because it only replaces the entire phrase "the cloud", with the space in the middle and everything.  However, there are derivatives of this project that replace the word "cloud" on its own and this should probably be filed as a bug with them.
