### ISSUE TITLE
Doesn't work on Gmail or Outlook?

### ISSUE THREAD

**Issue by yan-michael** [panicsteve/cloud-to-butt#71]
This extension is super great, but it doesn't seem to work on both gmail and outlook? Any ideas as to why that may be?

**Comment by panicsteve** [comment]
My guess would be that it's because GMail and Outlook are highly dynamic sites that continue to load & unload content after the containing page itself has "finished" loading.  cloud-to-butt won't see those changes without additional code to monitor the page in an ongoing way.  It's probably not worth the effort for such a silly joke, but if someone wants to fork and add that, I'm not going to stop them!
